force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoices__c/Invoices__c.object-meta.xml
<CustomObject>
    <label>Invoices</label>
    <nameField>
        <label>Invoices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoices__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoices__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoices__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JsonGeneraterTest.cls
@isTest
private  class JsonGeneraterTest {
    @isTest
    private static void sendContacts(){
        Account testAccount = new Account(
            Name='Akhilesh',
            Phone='9844818037',
            Email__c='akhilesh.h.n@gmail.com'
        );
        insert testAccount;
        Opportunity testOpportunity = new Opportunity(
            Name='Sales',
            Amount=1000000,
            CloseDate= Date.newInstance(2022,02,18),
            AccountId=testAccount.Id,
            StageName='Perception Analysis'
        );
        insert testOpportunity;
        
        Invoices__c testInvoice = new Invoices__c(
            Date__c=Date.newInstance(2022, 02, 19),
            Due_Date__c= Date.newInstance(2022, 02, 18),
            Status__c= 'DRAFT',
            Total__c=100000,
            Account__c=testAccount.Id,
            Opportunity__c=testOpportunity.Id
        );
        insert testInvoice;
         test.startTest();
       String xeroRef ='43c57c67-e106-45a9-bedc-ecbe21e45320';
        boolean result = JsonGenerater.sendContacts(testAccount.Id, xeroRef, testOpportunity.Id);
        
        System.assertEquals(true, result);
           test.stopTest();
    }
    
}